_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "models/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("rope3d_train",) # ("data/rope3d/rope3d_train.pkl",)
  TEST:  ("rope3d_val",) # ("data/rope3d/rope3d_val.pkl",) 
SOLVER:
  STEPS: (350000, 420000)
  MAX_ITER: 450000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
